import type {Metadata} from "next";
import "./globals.css";
import React, {JSX} from "react";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({children}: Readonly<{ children: React.ReactNode }>): JSX.Element {
    return (
        <html lang="ru">
        <body>
        {children}
        </body>
        </html>
    )
}
